[package]
name = "kettle-render"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
alacritty_terminal = "0.26.0"
anyhow.workspace = true
bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.11.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
kettle-config = { version = "0.1.0", path = "../kettle-config" }
kettle-core = { version = "0.1.0", path = "../kettle-core" }
log.workspace = true
pollster = "0.4.0"
raw-window-handle = "0.6.2"
unicode-width.workspace = true
wgpu = "29.0.3"
