//! kettle — a fast, cross-platform GPU terminal emulator.

use clap::Parser;

/// Version string shown by `kettle --version`. Concatenates the
/// `Cargo.toml` version with the git SHA captured by `build.rs` (or
/// the empty string when we're not in a git checkout — source
/// tarballs, vendored builds), so the output is one of:
///
/// - `kettle 0.1.0 (a1b2c3d4e5f6)` — git checkout, sha12 in parens.
/// - `kettle 0.1.0` — non-git build; concat with an empty string
///   leaves the version pristine. Cycle 192.
const KETTLE_VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), env!("KETTLE_GIT_SHA"));

#[derive(Parser, Debug)]
#[command(
    name = "kettle",
    version = KETTLE_VERSION,
    about = "A fast cross-platform GPU terminal emulator"
)]
struct Cli {
    /// List every bundled theme and exit.
    #[arg(long)]
    list_themes: bool,

    /// Print the keymap (trigger → action) and exit. Honors `--config FILE`
    /// to show the *effective* keymap after overrides + unbinds; without it,
    /// shows the built-in defaults.
    #[arg(long)]
    list_keybinds: bool,

    /// Print every accepted action name (for `keybind = trigger=action`) and exit.
    #[arg(long)]
    list_actions: bool,

    /// Print configured `ssh-host = name=target` entries (Ctrl+Shift+S launcher) and exit.
    #[arg(long)]
    list_ssh_hosts: bool,

    /// Print the resolved config path and exit.
    #[arg(long)]
    config_path: bool,

    /// Print the wgpu adapter / backend / driver / texture-limit
    /// details kettle would use on this machine, then exit. Useful
    /// for filing a "blank window" / "no GPU adapter" bug report
    /// without a windowed run.
    #[arg(long)]
    gpu_info: bool,

    /// Validate the config (resolved settings + unknown-key warnings).
    #[arg(long)]
    check_config: bool,

    /// Print the documented example config (`docs/kettle.example.config`)
    /// to stdout and exit. Pipe to your config path to bootstrap a fully
    /// commented starter file:
    ///
    ///   kettle --print-default-config > ~/.config/kettle/config
    ///
    /// Everything in the file is commented out — uncomment what you want
    /// to change. Re-read the file by either restarting kettle or
    /// triggering the in-window reload chord.
    #[arg(long, verbatim_doc_comment)]
    print_default_config: bool,

    /// Print the OSC 133 shell-integration snippet for SHELL (one of
    /// `bash`, `zsh`, `fish`) and exit. Append to your shell rc file
    /// to enable `Ctrl+Up` / `Ctrl+Down` jump-to-prompt:
    ///
    ///   kettle --shell-integration bash >> ~/.bashrc
    ///   kettle --shell-integration zsh  >> ~/.zshrc
    ///   kettle --shell-integration fish >> ~/.config/fish/config.fish
    ///
    /// Snippets live at `shell-integration/kettle.{bash,zsh,fish}` in
    /// the source tree and are embedded at build time so the binary
    /// always emits the version that shipped with it (`cargo install
    /// kettle` users included).
    #[arg(long, value_name = "SHELL", verbatim_doc_comment)]
    shell_integration: Option<String>,

    /// Print a shell completion script for SHELL (one of `bash`, `zsh`,
    /// `fish`, `elvish`, `powershell`) and exit. Append or source from
    /// your shell rc file to enable tab completion of every kettle CLI
    /// flag — `kettle --li<TAB>` → `--list-themes` / `--list-keybinds`
    /// / `--list-actions` / `--list-ssh-hosts`:
    ///
    ///   kettle --print-completions bash >> ~/.bashrc
    ///   kettle --print-completions zsh  > "${fpath[1]}/_kettle"
    ///   kettle --print-completions fish > ~/.config/fish/completions/kettle.fish
    ///
    /// The script is generated by `clap_complete` from the same `Cli`
    /// struct that powers `--help`, so a future flag automatically
    /// gets a completion.
    //
    // `${fpath[1]}` in the doc-comment above is zsh array-indexing
    // syntax, not a markdown reference link — silence the rustdoc
    // `broken_intra_doc_links` warning so the user-facing example
    // stays correct (and copy-pasteable) without inserting escape
    // characters that would leak into `--help` output.
    #[arg(long, value_name = "SHELL", verbatim_doc_comment)]
    #[allow(rustdoc::broken_intra_doc_links)]
    print_completions: Option<String>,

    /// Render a representative frame offscreen to a PNG and exit (no window).
    #[arg(long, value_name = "PATH")]
    screenshot: Option<std::path::PathBuf>,

    /// Render like `--screenshot` but with a synthetic right-click
    /// context menu open over the rendered pane. Useful for verifying
    /// the menu's render path without opening the windowed app, and
    /// for visual-regression tests in CI. Honors `--cols` / `--rows`
    /// / `--config` the same as `--screenshot`. PNG-only.
    #[arg(long, value_name = "PATH")]
    screenshot_menu: Option<std::path::PathBuf>,

    /// Caption text to overlay at the bottom of `--screenshot` /
    /// `--screenshot-menu` output (iTerm2 "annotated screenshot"
    /// parity). Useful for docs / README hero images / bug
    /// reports that want a version / repro / env note baked into
    /// the PNG. Example:
    ///
    ///   kettle --screenshot doc.png --annotate "kettle v1.3.x — TokyoNight Night"
    #[arg(long, value_name = "TEXT", verbatim_doc_comment)]
    annotate: Option<String>,

    /// Columns for `--screenshot` (default 96).
    #[arg(long, default_value_t = 96)]
    cols: u32,

    /// Rows for `--screenshot` (default 28).
    #[arg(long, default_value_t = 28)]
    rows: u32,

    /// Use this config file instead of the default path. Honored by every
    /// introspection command (`--check-config`, `--list-keybinds`,
    /// `--list-ssh-hosts`, `--screenshot`, `--config-path`) as well as the
    /// windowed run. The path must be an existing, regular, readable
    /// file: a missing path is a hard error, a directory is a hard error
    /// (typing `--config ~/.config/kettle` when you meant the file inside
    /// it), and a permission-denied file is a hard error too. The
    /// out-of-the-box default-path fallback only kicks in when this flag
    /// is omitted entirely.
    #[arg(long = "config", value_name = "FILE")]
    config: Option<std::path::PathBuf>,

    /// Working directory for the first tab (`-d DIR`).
    #[arg(long = "working-directory", short = 'd', value_name = "DIR")]
    working_directory: Option<std::path::PathBuf>,

    /// Launch into a named layout (Terminator parity). Saves +
    /// restores from `<config-dir>/layouts/<NAME>.json` so a user
    /// can maintain distinct workspaces ("dev", "ops", "docs")
    /// without each one clobbering the others on close. Example:
    ///
    ///   kettle --layout dev
    ///
    /// The name is sanitized to `[A-Za-z0-9._-]` at the session
    /// layer so a `--layout ../../etc/passwd` can't traverse out
    /// of the layouts directory.
    #[arg(long, value_name = "NAME", verbatim_doc_comment)]
    layout: Option<String>,

    /// Launch with a named-profile *config* (distinct from --layout
    /// which picks the *session*). Loads
    /// `<config-dir>/profiles/<NAME>.config` instead of the default
    /// `<config-dir>/config`. Lets a user keep distinct
    /// font/theme/keybind sets per workspace:
    ///
    ///   kettle --profile dark    # uses profiles/dark.config
    ///   kettle --profile light --layout docs
    ///
    /// `--config` takes precedence over `--profile` if both are
    /// given. Name is sanitized to `[A-Za-z0-9._-]` so a
    /// `--profile ../../etc/passwd` can't traverse out.
    #[arg(long, value_name = "NAME", verbatim_doc_comment)]
    profile: Option<String>,

    /// One-off accent color (peacock parity — distinguishes multi-
    /// window kettle setups visually). Overrides the tab-bar accent
    /// strip + dragged-tab ghost + focused-pane border. Accepts
    /// `#rrggbb`, `#rgb`, `0xRRGGBB`, or an X11 color name —
    /// whatever `Rgb::parse` accepts. Example:
    ///
    ///   kettle --accent '#ff6b35' --layout dev
    ///   kettle --accent teal --layout ops
    ///
    /// For persistent assignment, put `accent-color = #ff6b35` in
    /// a `<config-dir>/profiles/<NAME>.config` and launch via
    /// `--profile <NAME>`. `--accent` always wins over the config
    /// `accent-color` key when both are set.
    #[arg(long, value_name = "COLOR", verbatim_doc_comment)]
    accent: Option<String>,

    /// Toggle the running kettle window's visibility (Quake /
    /// Yakuake / Tilda dropdown UX) via the remote-control IPC and
    /// exit. Bind this to your compositor / DE / OS global hotkey
    /// to get a true dropdown terminal:
    ///
    ///   # GNOME: Settings → Keyboard → Custom Shortcuts → kettle --toggle
    ///   # KDE:   System Settings → Shortcuts → Custom → kettle --toggle
    ///   # Sway:  bindsym $mod+grave exec kettle --toggle
    ///   # Hyprland: bind = SUPER, grave, exec, kettle --toggle
    ///   # macOS: Karabiner / Raycast → run "kettle --toggle"
    ///   # Win11: PowerToys Keyboard Manager → kettle --toggle
    ///
    /// Sidesteps the cross-platform global-hotkey problem — each
    /// user picks the binding their setup already honors. Honors
    /// the same `--remote-file PATH` arbitration as `--remote-send`.
    #[arg(long, verbatim_doc_comment)]
    toggle: bool,

    /// Send TEXT to a running kettle via the remote-command file
    /// (default `<config-dir>/kettle/remote.cmd`) and exit. Used by
    /// external scripts to drive an already-open kettle without
    /// launching a new window (kitty `@ send-text` parity). Example:
    ///
    ///   kettle --remote-send 'ls -la\n'
    ///
    /// The receiving kettle window must have been launched with
    /// the same `--remote-file PATH` (or both omit it to use the
    /// default path). The text is written to the focused pane of
    /// the most-recently-launched kettle that's watching the file.
    /// Multi-window arbitration is "last writer wins" for now;
    /// per-window socket addressing is a planned follow-up.
    #[arg(long, value_name = "TEXT", verbatim_doc_comment)]
    remote_send: Option<String>,

    /// Remote-command file path. Default
    /// `<config-dir>/kettle/remote.cmd`. Honored by both the
    /// `--remote-send` sender side and the kettle window's
    /// notify-watcher receiver side; both must agree on the path.
    /// See `--remote-send` above for the usage example.
    #[arg(long, value_name = "PATH")]
    remote_file: Option<std::path::PathBuf>,

    /// Run this command in the first tab instead of the shell, e.g.
    /// `kettle -e htop` or `kettle -e ssh box`. Consumes the rest of the
    /// arguments (hyphenated flags for the program are passed through).
    #[arg(short = 'e', long = "exec", num_args = 1.., allow_hyphen_values = true, value_name = "CMD")]
    exec: Vec<String>,
}

/// Restore SIGPIPE to its default behavior on Unix. Rust's runtime sets
/// SIGPIPE to SIG_IGN at startup, which turns `println!` into a panic when
/// the reader of a pipeline (e.g. `kettle --list-themes | head`) closes
/// its end early. SIG_DFL makes the process exit silently on EPIPE —
/// which is what every other CLI tool does, and what shells expect when
/// chaining commands.
#[cfg(unix)]
fn reset_sigpipe() {
    // SAFETY: `signal` is async-signal-safe and we're calling it before
    // any threads spawn (very top of `main`), so there's no race window.
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }
}
#[cfg(not(unix))]
fn reset_sigpipe() {}

fn main() -> anyhow::Result<()> {
    reset_sigpipe();
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("warn")).init();
    // Cycle 204: log the build identity at info level on startup. A user
    // grep'ing their stderr for warnings to file a bug report can paste
    // the surrounding lines — the version line lands once near the top,
    // disambiguating which kettle build emitted the warning. `info` level
    // is below the `warn` default filter, so the line only appears when
    // the user has bumped logging (`RUST_LOG=info kettle …`); on the
    // default filter it stays out of the way.
    log::info!("kettle {KETTLE_VERSION} starting");
    let cli = Cli::parse();

    // Explicit `--config PATH` must point at a regular file. Every
    // downstream branch silently fell back to `Config::default()`
    // otherwise — the user got a screenshot / table / window with
    // their carefully-crafted theme nowhere in sight and no clue why.
    //
    // Cycle 106 caught the "no such file" case. Cycle 164 extends the
    // check to *not a regular file* (typically a directory — a user
    // typing `--config ~/.config/kettle` instead of
    // `--config ~/.config/kettle/config` would have `read_to_string`
    // return an `IsADirectory` error, the diagnostics path would
    // log a warning and use defaults, and the user would see the
    // same "my config didn't apply" symptom as the no-such-file
    // case). Same shape as `--working-directory` below: existence
    // is necessary but not sufficient — also gate on the right type.
    // Omitting `--config` (relying on the default path) still
    // silently falls back to defaults; that's the intended
    // "kettle works out of the box" behavior.
    if let Some(p) = &cli.config
        && let Some(reason) = config_path_problem(p)
    {
        return Err(anyhow::anyhow!("--config {}: {reason}", p.display()));
    }
    // Same shape for `--working-directory DIR` (cycle 107). The engine
    // silently falls back to `$HOME` when the directory doesn't exist
    // (see `kettle_core::term::Terminal::new`: `Some(d) if is_dir =>
    // cmd.cwd(d)`, else HOME), so a typo'd `-d ~/projets` spawned the
    // shell in the user's home with no warning and no obvious cue that
    // the requested cwd was ignored. Hard-fail at the CLI surface
    // before the engine even runs; report whether the path is missing
    // (typo) or exists-but-isn't-a-directory (named a file by
    // mistake) so the user's fix is one keystroke away.
    if let Some(p) = &cli.working_directory {
        let kind = if !p.exists() {
            Some("no such file or directory")
        } else if !p.is_dir() {
            Some("not a directory")
        } else {
            None
        };
        if let Some(reason) = kind {
            return Err(anyhow::anyhow!(
                "--working-directory {}: {reason}",
                p.display()
            ));
        }
    }

    if cli.list_themes {
        for name in kettle_config::Theme::list() {
            println!("{name}");
        }
        return Ok(());
    }
    if cli.print_default_config {
        // Cycle 227: `kettle --print-default-config > ~/.config/kettle/config`
        // is the one-command bootstrap. The example file lives at
        // `docs/kettle.example.config` (also linked from README and
        // CONFIG.md); embedding it at build time means the binary
        // always emits the version that shipped with it — no
        // disk-read at runtime, no path-resolution surprises, and
        // `cargo install kettle` users get the correct content
        // even if the source tree is gone.
        print!("{}", include_str!("../../../docs/kettle.example.config"));
        return Ok(());
    }
    if let Some(shell) = cli.print_completions.as_deref() {
        // Cycle 237: clap_complete generates a shell-completion
        // script from the Cli derive — same source of truth as
        // `--help` so a new flag is auto-completed without a
        // manual table update.
        use clap::CommandFactory;
        use clap_complete::Shell;
        let s = match shell {
            "bash" => Shell::Bash,
            "zsh" => Shell::Zsh,
            "fish" => Shell::Fish,
            "elvish" => Shell::Elvish,
            "powershell" => Shell::PowerShell,
            other => {
                return Err(anyhow::anyhow!(
                    "--print-completions {other:?}: unknown shell \
                     (supported: bash, zsh, fish, elvish, powershell)"
                ));
            }
        };
        let mut cmd = Cli::command();
        clap_complete::generate(s, &mut cmd, "kettle", &mut std::io::stdout());
        return Ok(());
    }
    if let Some(shell) = cli.shell_integration.as_deref() {
        // Cycle 229: same shape as `--print-default-config`, but for
        // the OSC 133 shell-integration snippet. Embedded at build
        // time so `cargo install kettle` users (no source tree
        // accessible) get the right snippet, and so the binary's
        // output can never drift from the in-tree source of truth
        // under `shell-integration/`.
        let snippet = match shell {
            "bash" => include_str!("../../../shell-integration/kettle.bash"),
            "zsh" => include_str!("../../../shell-integration/kettle.zsh"),
            "fish" => include_str!("../../../shell-integration/kettle.fish"),
            other => {
                return Err(anyhow::anyhow!(
                    "--shell-integration {other:?}: unknown shell \
                     (supported: bash, zsh, fish)"
                ));
            }
        };
        print!("{snippet}");
        return Ok(());
    }
    if cli.list_ssh_hosts {
        // Companion to --check-config (which reports a count) and the
        // Ctrl+Shift+S launcher (which lists them in-window): users
        // configuring a bunch of hosts wanted to verify the parse
        // *from the CLI* without launching kettle. Same `--config FILE`
        // override convention as the rest of the introspection
        // commands; falls back to the default config path.
        let cfg = match cli
            .config
            .clone()
            .or_else(kettle_config::Config::default_path)
        {
            Some(p) if p.exists() => kettle_config::Config::load_from(&p),
            _ => kettle_config::Config::default(),
        };
        for line in format_ssh_hosts(&cfg.ssh_hosts) {
            println!("{line}");
        }
        return Ok(());
    }
    if cli.list_actions {
        // Onboarding pair to `--list-keybinds`: that one shows what's
        // currently bound; this one shows what `keybind = trigger=…`
        // values are valid. Without this, users writing a new bind had
        // to grep the source or hit `--check-config` to confirm a name
        // they guessed. `goto_tab:N` is parametric, so it gets a
        // one-line tail blurb instead of an enumeration.
        for name in kettle_config::keybinds::action_names() {
            println!("{name}");
        }
        println!("goto_tab:N    (parametric; N is 1-based, 1..=255)");
        println!("unbind        (sentinel; removes the default — also: none, null, false, empty)");
        return Ok(());
    }
    if cli.list_keybinds {
        // Honor `--config FILE` (and the default config path if it
        // exists) so users see their *effective* keymap — defaults +
        // their overrides + their unbinds — not just the built-in set.
        // Previously a user who had spent time customizing their config
        // had to restart kettle and inspect by hand to confirm a
        // `keybind = …` line took effect; now they can introspect from
        // the CLI in one shot.
        let lines = match cli
            .config
            .clone()
            .or_else(kettle_config::Config::default_path)
        {
            Some(p) if p.exists() => {
                let cfg = kettle_config::Config::load_from(&p);
                kettle_config::keybinds::describe(&cfg.keybinds)
            }
            _ => kettle_config::keybinds::describe_defaults(),
        };
        for line in lines {
            println!("{line}");
        }
        return Ok(());
    }
    if cli.config_path {
        match cli
            .config
            .clone()
            .or_else(kettle_config::Config::default_path)
        {
            Some(p) => println!("{}", p.display()),
            None => println!("(no config path resolvable)"),
        }
        return Ok(());
    }
    if cli.gpu_info {
        // Resolves the same adapter / backend the live renderer +
        // --screenshot path would pick, so the output is faithful
        // to what the windowed run would see. No GUI / PTY needed.
        let info = kettle_render::gpu_info()?;
        println!("{info}");
        return Ok(());
    }
    if cli.check_config {
        // Cycle 312: honor `--profile NAME` here too. Pre-fix, the
        // resolution lookup only checked `cli.config` and fell back
        // to the default config path. A user running
        // `kettle --profile dev --check-config` would silently check
        // `<config-dir>/config` instead of `profiles/dev.config`,
        // missing typos the runtime path WOULD load. Mirrors the
        // windowed-run resolution at line 780+ — `--config FILE`
        // wins over `--profile NAME`, falls through to default when
        // both omitted.
        let path = cli
            .config
            .clone()
            .or_else(|| {
                cli.profile
                    .as_deref()
                    .and_then(kettle_config::Config::path_for_profile)
            })
            .or_else(kettle_config::Config::default_path);
        // Cycle 196: surface read errors explicitly. Pre-fix,
        // `load_from_with_diagnostics` silently returned defaults on
        // any read error (permission denied, ENOENT-after-stat-race,
        // I/O error) — the warn went to stderr but `--check-config`'s
        // stdout said "status: OK" and exited 0, making the user
        // think their config loaded. Now: probe `read_to_string`
        // directly and turn a read failure into a malformed entry
        // so it lands in the issues list with a non-zero exit code.
        // Cycle 197 (cycle 196 follow-up): drive parse_collect /
        // detect_malformed_values directly from the text we already
        // read, rather than calling `load_from_with_diagnostics`
        // which reads the file a SECOND time internally. Cycle 196's
        // first take did the read twice (once for the error probe,
        // once inside load_from_with_diagnostics). Harmless but
        // wasteful; now the read happens once.
        let mut read_error: Option<String> = None;
        let (cfg, unknown, malformed) = match &path {
            Some(p) if p.exists() => match std::fs::read_to_string(p) {
                Ok(text) => {
                    let (cfg, unknown) = kettle_config::Config::parse_collect(&text);
                    let malformed = kettle_config::Config::detect_malformed_values(&text);
                    (cfg, unknown, malformed)
                }
                Err(e) => {
                    read_error = Some(format!("could not read {}: {e}", p.display()));
                    (kettle_config::Config::default(), Vec::new(), Vec::new())
                }
            },
            _ => (kettle_config::Config::default(), Vec::new(), Vec::new()),
        };
        // Cycle 194: lead with the kettle build version + git SHA, so a
        // user pasting `--check-config` output into a bug report doesn't
        // also need to run `--version` separately. Matches the
        // diagnostic-first-line convention `cargo --version`-style tools
        // use in their support flags.
        println!("kettle:  {KETTLE_VERSION}");
        match &path {
            Some(p) if p.exists() => println!("config:  {}", p.display()),
            Some(p) => {
                println!("config:  {} (not found — using defaults)", p.display());
                // Cycle 228: when no config exists at the resolved
                // default path, point the user at the bootstrap
                // one-liner. Without this, a newcomer who ran
                // `--check-config` and saw "using defaults" had to
                // know on their own that `--print-default-config`
                // (cycle 227) is the way to create one. The hint
                // names the actual resolved path so copy-paste works.
                println!("hint:    kettle --print-default-config > {}", p.display());
            }
            None => println!("config:  (no path resolvable — using defaults)"),
        }
        println!("theme:   {}", cfg.theme_name);
        println!("font:    {} {}pt", cfg.font_family, cfg.font_size);
        println!("scrollback: {}", cfg.scrollback);
        println!("keybinds: {} bound", cfg.keybinds.len());
        // Echo back the resolved values of the per-cycle config gates so
        // users can verify with `kettle --check-config` that their tweaks
        // are taking effect (rather than greping the source). Grouped by
        // theme of related settings; only one line per group for brevity.
        println!(
            "cursor:  {:?} (blink={}, interval={}ms)",
            cfg.cursor_style, cfg.cursor_blink, cfg.cursor_blink_interval
        );
        println!(
            "bell:    {:?}  osc52: {:?}  min-contrast: {}",
            cfg.bell, cfg.osc52, cfg.minimum_contrast
        );
        println!(
            "scroll:  on-keystroke={} on-output={} multiplier={}",
            cfg.scroll_on_keystroke, cfg.scroll_on_output, cfg.scroll_multiplier
        );
        println!(
            "mouse:   hide-while-typing={} copy-on-select={}",
            cfg.mouse_hide_while_typing, cfg.copy_on_select
        );
        println!(
            "window:  padding={}x{} opacity={} unfocused-split={}",
            cfg.padding_x, cfg.padding_y, cfg.background_opacity, cfg.unfocused_split_opacity
        );
        // Split-color overrides are individually opt-in (default = theme
        // palette[4]/[8]); only echo when the user actually set one, so
        // common defaulted configs stay terse.
        if cfg.focused_split_color.is_some() || cfg.split_divider_color.is_some() {
            let f = cfg
                .focused_split_color
                .map(|c| format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b))
                .unwrap_or_else(|| "(theme)".into());
            let d = cfg
                .split_divider_color
                .map(|c| format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b))
                .unwrap_or_else(|| "(theme)".into());
            println!("splits:  focused={f} divider={d}");
        }
        println!(
            "tabs:    bar={:?} pos={:?} format={:?}",
            cfg.tab_bar, cfg.tab_bar_pos, cfg.tab_format
        );
        println!("title:   format={:?}", cfg.window_title_format);
        if !cfg.word_delimiters.is_empty() {
            println!("words:   {:?}", cfg.word_delimiters);
        }
        if !cfg.ssh_hosts.is_empty() {
            println!("ssh:     {} host(s) configured", cfg.ssh_hosts.len());
        }
        // Repeatable / opt-in keys: only echo when actually set so the
        // default-config case stays terse, but show the count when the
        // user has tuned them — otherwise `--check-config` silently
        // dropped `font-feature` / per-style font families / palette
        // overrides from its summary even when the user had taken the
        // time to configure them. Symmetric with the `ssh:` line above.
        if !cfg.font_features.is_empty() {
            println!(
                "font-features: {} configured (ligatures={})",
                cfg.font_features.len(),
                cfg.font_ligatures
            );
        }
        let styled_families = [
            ("bold", cfg.font_family_bold.as_deref()),
            ("italic", cfg.font_family_italic.as_deref()),
            ("bold-italic", cfg.font_family_bold_italic.as_deref()),
        ];
        let styles_set: Vec<&str> = styled_families
            .iter()
            .filter(|(_, v)| v.is_some())
            .map(|(k, _)| *k)
            .collect();
        if !styles_set.is_empty() {
            println!(
                "font-styles: per-style overrides for [{}]",
                styles_set.join(", ")
            );
        }
        // Cycle 201: count and display I/O errors (cycle 196's read
        // failures) as their own category rather than reusing the
        // "malformed value:" prefix — a permission-denied file isn't
        // a value-parsing failure, and labeling it as one was
        // confusing the diagnostic. Read errors get an `i/o error:`
        // line instead.
        let io_count = if read_error.is_some() { 1 } else { 0 };
        let issues = unknown.len() + malformed.len() + io_count;
        if issues == 0 {
            println!("status:  OK — no issues");
            return Ok(());
        }
        println!("status:  {issues} issue(s):");
        if let Some(e) = &read_error {
            println!("  - i/o error: {e} (using defaults)");
        }
        for k in &unknown {
            println!("  - unknown key: {k}");
        }
        for k in &malformed {
            println!("  - malformed value: {k}");
        }
        std::process::exit(1);
    }

    // Both `--screenshot` and `--screenshot-menu` (cycle 251) share
    // the same pre-validation + config load + capture path; the only
    // difference is the `DebugScene` passed to `capture_png_with`.
    // The flags are mutually exclusive — pick the first one set.
    let screenshot_target = cli
        .screenshot
        .as_ref()
        .map(|p| (p, kettle_render::DebugScene::Default, "--screenshot"))
        .or_else(|| {
            cli.screenshot_menu.as_ref().map(|p| {
                (
                    p,
                    kettle_render::DebugScene::ContextMenu,
                    "--screenshot-menu",
                )
            })
        });
    if let Some((out, scene, flag_name)) = screenshot_target {
        // The renderer's `capture_png` writes via `image::save`, which
        // dispatches on file extension and is compiled with PNG-only
        // support (kettle-render/Cargo.toml: `features = ["png"]`).
        // A typo'd `.jpg` / `.bmp` / no-extension argument used to
        // reach `image::save` and surface a crate-internal error like
        //   `The file extension `."txt"` was not recognized as an
        //   image format`
        // *after* doing all the GPU work — confusing and wasted. Pre-
        // validate so the message is clear and the failure is cheap.
        // Cycle 128.
        match out.extension().and_then(|e| e.to_str()) {
            Some(e) if e.eq_ignore_ascii_case("png") => {}
            Some(e) => {
                return Err(anyhow::anyhow!(
                    "{flag_name} {}: extension .{e} not supported; \
                     only .png is built in",
                    out.display()
                ));
            }
            None => {
                return Err(anyhow::anyhow!(
                    "{flag_name} {}: missing .png extension",
                    out.display()
                ));
            }
        }
        // Use `load_from` (same path the in-window reload uses) instead
        // of an open-coded `parse_collect`: now a typo in the config
        // emits the same `log::warn!` on stderr when generating a
        // screenshot as it does when running interactively. Previously
        // `--screenshot` was the only flag that silently swallowed
        // both unknown keys *and* malformed values, which made it
        // confusing when a screenshot didn't reflect what the user
        // thought their config said.
        let mut cfg = match cli
            .config
            .clone()
            .or_else(kettle_config::Config::default_path)
        {
            Some(p) if p.exists() => kettle_config::Config::load_from(&p),
            _ => kettle_config::Config::default(),
        };
        // Cycle 293: --accent CLI flag wins over the config
        // `accent-color` key for screenshots too, so a user
        // generating per-workspace docs gets the accent applied
        // without editing a config file.
        if let Some(rgb) = cli.accent.as_deref().and_then(kettle_config::Rgb::parse) {
            cfg.accent_color = Some(rgb);
        }
        // Clamp dimensions to a sane range — wgpu textures cap at 8192 px
        // per side on most GPUs, so a typo like `--cols 100000` used to
        // panic with `dimension X exceeds the limit of 8192` instead of
        // producing a friendly error. Worst-case cell size ~20 px wide /
        // ~40 px tall keeps 400×200 cells comfortably under the limit;
        // every realistic screenshot fits.
        let cols = cli.cols.clamp(20, 400);
        let rows = cli.rows.clamp(8, 200);
        // `capture_png_with` may shrink (cols, rows) further to fit
        // the GPU texture limit at the active font size; show what
        // was actually rendered, with a hint when it differs from the
        // request so the user notices their cli args didn't fully
        // apply.
        let (actual_cols, actual_rows) = kettle_render::capture_png_with_annotation(
            &cfg,
            cols,
            rows,
            out,
            scene,
            cli.annotate.as_deref(),
        )?;
        if actual_cols == cols && actual_rows == rows {
            println!("wrote {} ({cols}×{rows} cells)", out.display());
        } else {
            println!(
                "wrote {} ({actual_cols}×{actual_rows} cells — \
                 capped from {cols}×{rows} for GPU texture limit at \
                 current font size)",
                out.display()
            );
        }
        return Ok(());
    }

    // Cycle 303 Quake dropdown: `--toggle` is sugar for `--remote-send`
    // with a fixed `toggle-window` command. Same path-resolution
    // (--remote-file or default) so a user can bind their global
    // hotkey to `kettle --toggle` without any extra config.
    if cli.toggle {
        let path = cli
            .remote_file
            .clone()
            .or_else(default_remote_file)
            .ok_or_else(|| anyhow::anyhow!("could not resolve default remote-file path"))?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        use std::io::Write;
        let mut f = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)?;
        f.write_all(b"toggle-window\n")?;
        return Ok(());
    }

    // Cycle 302 remote-control SENDER side. When `--remote-send TEXT`
    // is set, append TEXT (with trailing newline if missing) to the
    // remote-command file and exit without launching a window. The
    // running kettle that's watching the file picks up the line and
    // dispatches `send-text <REST>` to its focused pane.
    if let Some(text) = cli.remote_send.as_deref() {
        let path = cli
            .remote_file
            .clone()
            .or_else(default_remote_file)
            .ok_or_else(|| anyhow::anyhow!("could not resolve default remote-file path"))?;
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Each line is one command: `send-text <TEXT>\n`. Escape any
        // embedded newlines as `\\n` so a multi-line payload doesn't
        // get re-parsed as multiple commands. The receiver decodes
        // `\\n` back to `\n` before writing to the PTY.
        let encoded = text.replace('\n', "\\n");
        let line = format!("send-text {encoded}\n");
        use std::io::Write;
        let mut f = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&path)?;
        f.write_all(line.as_bytes())?;
        return Ok(());
    }

    // Resolve --profile if --config didn't override it. --config wins
    // when both are given so a user can quickly debug a profile
    // against an explicit config file.
    let config_path = cli.config.or_else(|| {
        cli.profile
            .as_deref()
            .and_then(kettle_config::Config::path_for_profile)
    });
    // --accent parses via the same Rgb parser the config uses, so
    // every format the config key accepts (#rrggbb / #rgb / 0xRRGGBB
    // / X11 names) works on the CLI too. A malformed value silently
    // falls through to the config's accent-color (or palette[4]) —
    // same shape as the config parse arm, no hard fail.
    let accent_override = cli.accent.as_deref().and_then(kettle_config::Rgb::parse);
    let remote_file = cli.remote_file.clone().or_else(default_remote_file);
    kettle_ui::run_with(kettle_ui::Options {
        command: (!cli.exec.is_empty()).then_some(cli.exec),
        cwd: cli.working_directory,
        config: config_path,
        layout: cli.layout,
        accent_override,
        remote_file,
    })
}

/// Cycle 302: default remote-command file path. Lives under the
/// kettle config directory so `--remote-send` / `--remote-file`
/// callers and the kettle window's watcher agree without explicit
/// paths on either side. None when the config dir isn't resolvable
/// (no $HOME / $XDG_CONFIG_HOME) — same shape as
/// `Config::default_path`.
fn default_remote_file() -> Option<std::path::PathBuf> {
    kettle_config::Config::default_path().and_then(|p| p.parent().map(|d| d.join("remote.cmd")))
}

/// Render `ssh-host` entries as the `--list-ssh-hosts` table: alphabetical
/// by name, two columns aligned to the longest name (floor 4 so single-
/// Validate a `--config PATH` argument: must be an existing regular file
/// the current process can open. Returns `None` when the path is acceptable,
/// or `Some(reason)` ready to slot into the CLI error template. Pure-modulo-
/// the-filesystem so the typo / wrong-kind / unreadable paths (no such file,
/// directory mistyped for the file inside, perm-denied file) are unit-
/// testable without spawning the binary. The matching `--working-directory`
/// check is still inlined below — the messages differ (`not a regular file`
/// vs `not a directory`) and the call site is short enough; extracting both
/// into a shared kind-enum helper would add more glue than it removes.
///
/// Cycle 198: also probe `File::open` so a permission-denied file fails
/// at the CLI surface instead of at the silent runtime fallback. Cycles
/// 106 (no such file), 164 (not a regular file), 198 (unreadable) cover
/// the three classes of "user typed `--config FILE` but kettle ignored
/// it" complaints.
fn config_path_problem(p: &std::path::Path) -> Option<&'static str> {
    if !p.exists() {
        Some("no such file")
    } else if !p.is_file() {
        Some("not a regular file")
    } else if std::fs::File::open(p).is_err() {
        Some("not readable (permission denied or I/O error)")
    } else {
        None
    }
}

/// character names don't collapse the column), padded with two spaces.
/// Empty input yields a single "(no ssh-host entries configured)" line so
/// the user sees their config is empty rather than no output at all.
/// Pure so the formatting is unit-testable without the CLI.
fn format_ssh_hosts(hosts: &[(String, String)]) -> Vec<String> {
    if hosts.is_empty() {
        return vec!["(no ssh-host entries configured)".into()];
    }
    let width = hosts.iter().map(|(n, _)| n.len()).max().unwrap_or(0).max(4);
    let mut rows: Vec<(&str, &str)> = hosts
        .iter()
        .map(|(n, t)| (n.as_str(), t.as_str()))
        .collect();
    rows.sort_unstable();
    rows.into_iter()
        .map(|(name, target)| format!("{name:<width$}  {target}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{Cli, config_path_problem, format_ssh_hosts};
    use clap::Parser;

    #[test]
    fn config_path_problem_catches_missing_and_directory() {
        use std::io::Write;
        // Missing path → "no such file" (cycle 106 shape; preserved).
        let missing = std::path::PathBuf::from("/definitely/not/a/real/path/kettle.conf");
        assert_eq!(config_path_problem(&missing), Some("no such file"));

        // Real temp dir: `--config DIR` was the cycle 164 gap. Pre-fix,
        // `--config ~/.config/kettle` (where the file is `.config/kettle/config`
        // and the user dropped the trailing component) silently fell back to
        // defaults — `read_to_string` returned IsADirectory, `load_from_with_diagnostics`
        // logged a warn and used defaults, and the user saw their carefully-
        // crafted theme nowhere with no obvious cue why.
        let tmp = std::env::temp_dir().join(format!("kettle-cycle164-{}", std::process::id()));
        std::fs::create_dir_all(&tmp).unwrap();
        assert_eq!(config_path_problem(&tmp), Some("not a regular file"));

        // Real regular file inside the temp dir → acceptable (None).
        let file = tmp.join("config");
        std::fs::File::create(&file)
            .unwrap()
            .write_all(b"theme = TokyoNight Night\n")
            .unwrap();
        assert_eq!(config_path_problem(&file), None);

        // Cycle 198: unreadable file (perm-denied) is rejected at the
        // CLI surface so the runtime doesn't silently fall back to
        // defaults. Skip on Windows / CI users where chmod-000 doesn't
        // actually deny read to the calling user.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let unreadable = tmp.join("unreadable.conf");
            std::fs::File::create(&unreadable)
                .unwrap()
                .write_all(b"theme = TokyoNight Night\n")
                .unwrap();
            std::fs::set_permissions(&unreadable, std::fs::Permissions::from_mode(0o000)).unwrap();
            // The check should now flag it. Root bypasses unix perms,
            // so only assert when we actually can't open it ourselves
            // — running CI as root would otherwise spuriously fail
            // the test.
            if std::fs::File::open(&unreadable).is_err() {
                assert_eq!(
                    config_path_problem(&unreadable),
                    Some("not readable (permission denied or I/O error)"),
                );
            }
            // Restore perms so the cleanup remove can succeed.
            let _ = std::fs::set_permissions(&unreadable, std::fs::Permissions::from_mode(0o644));
            let _ = std::fs::remove_file(&unreadable);
        }

        // Cleanup so a re-run of the suite starts fresh.
        let _ = std::fs::remove_file(&file);
        let _ = std::fs::remove_dir(&tmp);
    }

    #[test]
    fn print_completions_emits_per_shell_scripts() {
        // Cycle 237: clap_complete's output is per-shell shaped.
        // Pin the contract: each known shell emits a non-trivial
        // script that mentions kettle's command name. A regression
        // (e.g. someone passes the wrong Shell variant, or the
        // generator silently emits empty) would otherwise only
        // surface for a user trying to actually use the completion.
        //
        // Run via the same code path as `main` — `Cli::command()` +
        // `clap_complete::generate`.
        use clap::CommandFactory;
        use clap_complete::Shell;
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let mut cmd = Cli::command();
            let mut out: Vec<u8> = Vec::new();
            clap_complete::generate(shell, &mut cmd, "kettle", &mut out);
            let text = String::from_utf8(out).expect("utf8");
            assert!(
                text.len() > 200,
                "{shell:?} completion is too small ({} bytes) — \
                 generator likely degraded",
                text.len()
            );
            assert!(
                text.contains("kettle"),
                "{shell:?} completion doesn't mention `kettle` — \
                 wrong command name plumbed through"
            );
        }
    }

    #[test]
    fn shell_integration_snippets_match_in_tree_files() {
        // Cycle 229: `kettle --shell-integration <shell>` emits one
        // of the embedded `shell-integration/kettle.{bash,zsh,fish}`
        // files. The contract: the embedded content must equal the
        // in-tree file byte-for-byte (so docs/SHELL-INTEGRATION.md
        // and `--shell-integration` never diverge) and each snippet
        // must include the OSC 133 prefix (catches an accidental
        // truncated include_str! at build time).
        for (shell, embedded) in [
            (
                "bash",
                include_str!("../../../shell-integration/kettle.bash"),
            ),
            ("zsh", include_str!("../../../shell-integration/kettle.zsh")),
            (
                "fish",
                include_str!("../../../shell-integration/kettle.fish"),
            ),
        ] {
            assert!(
                embedded.contains("OSC 133")
                    && (embedded.contains("\\033]133") || embedded.contains("\\e]133")),
                "{shell}: embedded snippet missing OSC 133 marker — \
                 the file's body probably regressed"
            );
            assert!(
                embedded.lines().count() >= 10,
                "{shell}: snippet has only {} lines — likely empty \
                 include_str!",
                embedded.lines().count()
            );
        }
    }

    #[test]
    fn print_default_config_round_trip() {
        // Cycle 227: `kettle --print-default-config` emits the
        // embedded `docs/kettle.example.config`. The first-launch
        // bootstrap is:
        //   kettle --print-default-config > ~/.config/kettle/config
        // Pin the contract that:
        //   1. The embedded content is non-trivial (≥ 50 lines) so
        //      we catch an accidental empty include_str! at build
        //      time rather than at "ship time".
        //   2. It is a valid kettle config — Config::parse_collect
        //      reports zero unknown-key / malformed-value
        //      diagnostics. Everything in the example file is
        //      commented out by convention (cycle 100 drift guard),
        //      so the only requirement is the parser accepts it.
        let embedded = include_str!("../../../docs/kettle.example.config");
        assert!(
            embedded.lines().count() >= 50,
            "embedded example config has only {} lines — \
             include_str! probably stale",
            embedded.lines().count()
        );
        let (_, diags) = kettle_config::Config::parse_collect(embedded);
        assert!(
            diags.is_empty(),
            "embedded example config emits diagnostics: {diags:?}"
        );
    }

    #[test]
    fn format_ssh_hosts_sorts_and_aligns_columns() {
        // Empty case: explicit message rather than an empty Vec (so the
        // CLI prints something the user can see, not silence).
        assert_eq!(
            format_ssh_hosts(&[]),
            vec!["(no ssh-host entries configured)".to_string()]
        );
        // Three rows, intentionally out of order, with varying name lengths.
        let hosts = vec![
            ("box".to_string(), "me@box.example.com".to_string()),
            ("a".to_string(), "u@h".to_string()),
            ("work-vpn".to_string(), "admin@10.0.0.5".to_string()),
        ];
        let out = format_ssh_hosts(&hosts);
        // Sorted alphabetically by name.
        assert_eq!(
            out,
            vec![
                "a         u@h".to_string(),
                "box       me@box.example.com".to_string(),
                "work-vpn  admin@10.0.0.5".to_string(),
            ]
        );
        // Column width = longest name (`work-vpn` = 8) — minimum 4 for
        // short-name configs. Use a tiny single-row case to pin the floor.
        let tiny = vec![("a".to_string(), "u@h".to_string())];
        let out = format_ssh_hosts(&tiny);
        // Floor: 4 chars + two-space separator = "a   " + "  " + "u@h".
        assert_eq!(out, vec!["a     u@h".to_string()]);
    }

    #[test]
    fn cli_exec_and_working_directory_parse() {
        let c = Cli::try_parse_from([
            "kettle",
            "--config",
            "/etc/k.conf",
            "-d",
            "/tmp",
            "-e",
            "ssh",
            "-t",
            "box",
        ])
        .expect("valid args");
        assert_eq!(
            c.working_directory.as_deref(),
            Some(std::path::Path::new("/tmp"))
        );
        assert_eq!(
            c.config.as_deref(),
            Some(std::path::Path::new("/etc/k.conf"))
        );
        // `-e` consumes the rest, including hyphenated flags for the program.
        assert_eq!(c.exec, vec!["ssh", "-t", "box"]);
        // Defaults: no overrides.
        let d = Cli::try_parse_from(["kettle"]).unwrap();
        assert!(d.exec.is_empty() && d.working_directory.is_none() && d.config.is_none());
    }

    #[test]
    fn cli_help_text_has_no_internal_cycle_refs() {
        // `--help` is the very first contact most users have with the CLI.
        // Earlier cycles' rustdoc-style notes ("(cycle 103)", "(cycle 106)")
        // helped *me* trace audit history during development but leak as
        // mysterious-looking parentheticals when piped to a real terminal
        // user. The audit trail lives in CHANGELOG and code comments; the
        // user-facing help text should not.
        //
        // Walk every argument's long+short help string and assert none
        // contain "cycle " — same shape as cycle 116's
        // `defaults_has_no_shadow_collisions` drift guard, but for the
        // CLI's user-facing surface instead of the keybind defaults.
        use clap::CommandFactory;
        let cmd = Cli::command();
        for arg in cmd.get_arguments() {
            for txt in arg
                .get_help()
                .iter()
                .map(|s| s.to_string())
                .chain(arg.get_long_help().iter().map(|s| s.to_string()))
            {
                assert!(
                    !txt.to_ascii_lowercase().contains("cycle "),
                    "internal `cycle N` ref leaked into --help text for {:?}: {txt:?}",
                    arg.get_id(),
                );
            }
        }
        // Same for the top-level about/long-about strings.
        let about = cmd.get_about().map(|s| s.to_string()).unwrap_or_default();
        let long = cmd
            .get_long_about()
            .map(|s| s.to_string())
            .unwrap_or_default();
        for txt in [about, long] {
            assert!(
                !txt.to_ascii_lowercase().contains("cycle "),
                "internal `cycle N` ref leaked into --help about text: {txt:?}",
            );
        }
    }

    #[test]
    fn cli_help_preserves_indented_code_examples() {
        // A `#[arg(...)]` whose doc-comment contains an indented `  kettle …`
        // example must declare `verbatim_doc_comment` — otherwise clap
        // collapses the leading spaces in `--help`, flattening the example
        // back into prose. The original cycle 229 / 237 fixes covered
        // --shell-integration and --print-completions; --print-default-config
        // (added by cycle 227) had the same indented-example pattern and the
        // same wrapping bug, which is what this guard pins.
        //
        // Same shape as `cli_help_text_has_no_internal_cycle_refs` directly
        // above: walk the clap-built `Cli::command()`, pull each flag's
        // `get_long_help()`, assert the indented example survives literally.
        use clap::CommandFactory;
        let cmd = Cli::command();
        // Arg IDs match the struct field name, not the kebab-cased long flag.
        let expected = [
            ("shell_integration", "  kettle --shell-integration bash"),
            ("print_completions", "  kettle --print-completions bash"),
            ("print_default_config", "  kettle --print-default-config > "),
        ];
        for (id, needle) in expected {
            let arg = cmd
                .get_arguments()
                .find(|a| a.get_id().as_str() == id)
                .unwrap_or_else(|| panic!("no --{id} arg in CLI"));
            let long = arg
                .get_long_help()
                .map(|s| s.to_string())
                .unwrap_or_default();
            assert!(
                long.contains(needle),
                "--{id} lost the indented example {needle:?} — likely missing \
                 `verbatim_doc_comment` on its #[arg(...)] attribute. \
                 Rendered long_help:\n{long}",
            );
        }
    }

    #[test]
    fn man_page_documents_load_bearing_default_keybinds() {
        // Cycle 282 drift guard. The cycle-279 hand-written `kettle.1` man
        // page documents the default keybind set. Cycle 281 caught four
        // entries that had drifted from the actual defaults (`Ctrl+Shift+
        // arrow` was a scroll binding, not focus; `Ctrl+Shift+Z` /
        // `Ctrl+Shift+D` weren't default-bound at all). This guard pins
        // the man page against `--list-keybinds`'s ground truth so the
        // next time a default-keybind set changes (or the man page text
        // gets edited carelessly), CI fails instead of a user trying
        // `man kettle` + the documented hotkey getting a different
        // action.
        //
        // Check shape: every "load-bearing" (Trigger, Action) the default
        // config carries must have its Trigger string textually present
        // somewhere in the man page. We don't require the *Action* name
        // to appear — the man page uses human-readable prose ("new tab",
        // not `NewTab`). And we don't enforce the full keybind set —
        // the man page intentionally summarizes; binding additions
        // shouldn't fail the guard just because the doc didn't grow.
        //
        // The load-bearing list is the set of bindings a user typically
        // hits in the first hour: tab management, splits, focus, copy/
        // paste, scrollback movement, broadcast. If you add a NEW load-
        // bearing default and forget to document it, this test fails.
        const MAN_PAGE: &str = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packaging/linux/kettle.1"
        ));
        // The keybind triggers we expect documented. Strings are the
        // `Trigger`'s canonical display form as `kettle --list-keybinds`
        // prints them — see `kettle_config::keybinds::Trigger::Display`.
        let load_bearing: &[&str] = &[
            // Tabs
            "Ctrl+Shift+T", // NewTab
            "Ctrl+Shift+W", // ClosePane
            "Ctrl+PgUp",    // PrevTab (or accept "Ctrl+PageUp")
            "Ctrl+PgDn",    // NextTab
            // Splits
            "Ctrl+Shift+O", // SplitDown
            "Ctrl+Shift+E", // SplitRight
            // Focus
            "Alt+", // FocusUp / Down / Left / Right (any one suffices)
            // Overlays
            "Ctrl+Shift+K", // CommandPalette
            "Ctrl+Shift+F", // StartSearch
            "Ctrl+Shift+H", // HintMode
            "Ctrl+Shift+S", // OpenSsh
            // Clipboard
            "Ctrl+Shift+C", // Copy
            "Ctrl+Shift+V", // Paste
            // Scrollback
            "Ctrl+Up",   // JumpPrevPrompt
            "Ctrl+Down", // JumpNextPrompt
            // Zoom
            "Ctrl+Shift+X", // ToggleZoom
            // Broadcast
            "Super+G", // ToggleBroadcastAll
            // Vi-mode (cycle 298). The Ctrl+Shift+Space entry point
            // is load-bearing — without it, vi-mode users can't
            // enter the mode at all. h/j/k/l are mentioned in the
            // man page but not pinned here (they're the de-facto
            // vi keys, swapping them would be a deliberate config
            // override rather than a doc drift).
            "Ctrl+Shift+Space", // ToggleViMode
        ];
        let mut missing: Vec<&str> = Vec::new();
        for trigger in load_bearing {
            if !MAN_PAGE.contains(trigger) {
                missing.push(trigger);
            }
        }
        assert!(
            missing.is_empty(),
            "man page is missing load-bearing default keybinds: {missing:?}\n\
             Update packaging/linux/kettle.1 to document them (or change \
             this guard if a binding was intentionally removed)."
        );
    }
}
