"""Independent spot arithmetic. Does not import harness analysis or fill code."""
import math
import statistics

MIB = 1048576


def quantile(samples, fraction):
    ordered = sorted(samples)
    offset = (len(ordered) - 1) * fraction
    a = int(offset)
    b = min(a + 1, len(ordered) - 1)
    return ordered[a] * (b - offset) + ordered[b] * (offset - a) if a != b else ordered[a]


def typing(row):
    start, end = row['typing_start_ns'], row['typing_end_ns']
    interval = row['typing_sample_interval_ms']
    if interval != 100:
        raise ValueError('typing sample interval differs from frozen method')
    all_samples = row['typing_timeline']
    for a, b in zip(all_samples, all_samples[1:]):
        if b['scheduled_ns'] - a['scheduled_ns'] != interval * 1000000:
            raise ValueError('typing scheduled interval mismatch')
    retained = [s for s in all_samples if start <= s['query_start_ns'] <= s['query_end_ns'] <= end]
    expected = math.ceil((end - start) / (interval * 1000000))
    if (len(retained) < max(5, math.ceil(.8 * expected))
            or len(retained) != row['typing_sample_count'] or row['typing_expected_samples'] != expected):
        raise ValueError('typing coverage mismatch')
    marks = [start] + [s['query_end_ns'] for s in retained] + [end]
    if any(b - a > 250000000 for a, b in zip(marks, marks[1:])):
        raise ValueError('typing uncovered gap')
    return statistics.median(s['footprint'] / MIB for s in retained)


def spot_rows(results, require_typing=True):
    """Recompute startup, flood and typing rows; latency pools actual keys.

    Values are checked against retained round values, never against numbers
    generated by the production extractor a second time.
    """
    checked = set()
    for result in results:
        rows = result['workloads']
        for name, runs in rows.get('startup', {}).items():
            values = [r['child_ms'] for r in runs if not r.get('warmup') and 'child_ms' in r]
            if values:
                checked.add('startup.child_ms')
        for name, runs in rows.get('idle', {}).items():
            if any(r.get('frontmost') and r.get('footprint_mib') is not None for r in runs):
                checked.add('idle.footprint_mib')
        for name, runs in rows.get('flood-memory', {}).items():
            for row in runs:
                if row.get('warmup') or row.get('error'):
                    continue
                # Historical rounded timeline remains a descriptive check.
                if row.get('timeline'):
                    at = next((r for r in row['timeline'] if r[0] >= 3000), None)
                    if at is not None and abs(at[1] - row['done3_mib']) > .11:
                        raise ValueError('flood designated sample mismatch')
                checked.add('flood-memory.done3_mib')
        for name, runs in rows.get('latency', {}).items():
            for row in runs:
                if row.get('warmup') or row.get('error') or not row.get('typing_memory_valid'):
                    continue
                if abs(typing(row) - row['typing_footprint_mib']) > 1e-10:
                    raise ValueError('typing independent median mismatch')
                checked.add('latency.typing_footprint_mib')
    required = {'startup.child_ms', 'flood-memory.done3_mib'} | ({'latency.typing_footprint_mib'} if require_typing else {'idle.footprint_mib'})
    if not required <= checked:
        raise ValueError('independent spot rows unavailable')
    return sorted(checked)


def verify_estimates(results, combined):
    """Check each available session estimate using independent arithmetic."""
    by_label = {r['meta']['label']: r for r in results}
    for metric, row in combined['rows'].items():
        workload, field = metric.split('.', 1)
        for per in row['per_session']:
            result = by_label[per['label']]
            for name, expected in per['estimates'].items():
                if not per['metric_countable'].get(name, {}).get('countable'):
                    continue
                runs = [r for r in result['workloads'][workload].get(name, []) if not r.get('warmup') and not r.get('error') and (workload != 'idle' or r.get('frontmost'))]
                if workload in ('latency', 'latency-cursor') and field in ('mean_ms','median_ms','p95_ms','p99_ms'):
                    censor = (result['meta'].get(workload) or {}).get('censor_ms', 500)
                    launches = [list(r['samples_ms']) + [censor] * r.get('censored', 0) for r in runs]
                    pooled = [v for keys in launches for v in keys]
                    actual = statistics.mean(statistics.mean(keys) for keys in launches) if field == 'mean_ms' else quantile(pooled, {'median_ms':.5,'p95_ms':.95,'p99_ms':.99}[field])
                elif field == 'typing_footprint_mib':
                    actual = statistics.median(typing(r) for r in runs)
                elif workload == 'vtebench':
                    if field == 'geometric mean':
                        rounds = [math.exp(statistics.mean(math.log(v) for v in r['means_ms'].values())) for r in runs]
                    else:
                        rounds = [r['means_ms'][field] for r in runs]
                    actual = statistics.mean(rounds)
                elif field in ('input_ms', 'output_ms'):
                    values = [v for r in runs for v in r.get('inputs_ms' if field == 'input_ms' else 'outputs_ms', []) if v is not None]
                    actual = statistics.median(values)
                else:
                    values = [r[field] for r in runs if field in r and r[field] is not None]
                    if not values:
                        raise ValueError('independent estimate unavailable')
                    actual = statistics.median(values)
                if abs(actual - expected) > 1e-9:
                    raise ValueError('independent estimate mismatch: ' + metric)
    return True
