//! Generates a compile-time table of all bundled Ghostty themes so kettle ships
//! every theme with zero runtime file dependencies.

use std::env;
use std::fs;
use std::path::Path;

// Pulled in via `include!` so the *exact* same filter logic ships in the
// library (where it has unit tests) and is used by the build script (where
// the test harness isn't available). When you change the filter in one
// place it changes in both.
include!("src/theme_filter.rs");

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let themes_dir = Path::new(&manifest).join("../../assets/themes");
    println!("cargo:rerun-if-changed={}", themes_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&themes_dir) {
        for e in rd.flatten() {
            let path = e.path();
            if !path.is_file() {
                continue;
            }
            let name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };
            if !is_bundled_theme_filename(&name) {
                continue;
            }
            if let Ok(contents) = fs::read_to_string(&path) {
                entries.push((name, contents));
            }
        }
    }
    // Case-insensitive primary sort, case-sensitive tiebreak so the
    // final order is deterministic across runs. Before cycle 145
    // this was a raw `String::cmp` which sorted ASCII-bytewise —
    // putting all uppercase-starting themes ahead of all
    // lowercase-starting themes (`CGA` before `branch` because
    // 'C' < 'b' in ASCII). Users skimming `kettle --list-themes`
    // expect mixed-case alphabetical ("all the C-ish themes
    // together"), matching what GNU `sort` does in a UTF-8 locale.
    entries.sort_by(|a, b| {
        a.0.to_lowercase()
            .cmp(&b.0.to_lowercase())
            .then_with(|| a.0.cmp(&b.0))
    });

    let mut out = String::new();
    out.push_str("// @generated by build.rs\n");
    out.push_str(&format!(
        "pub static BUNDLED_THEMES: [(&str, &str); {}] = [\n",
        entries.len()
    ));
    for (name, contents) in &entries {
        out.push_str(&format!(
            "    ({:?}, {:?}),\n",
            name,
            contents.replace('\r', "")
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("themes_generated.rs"), out).unwrap();
}
