//! Generates a compile-time table of all bundled Ghostty themes so kettle ships
//! every theme with zero runtime file dependencies.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let themes_dir = Path::new(&manifest).join("../../assets/themes");
    println!("cargo:rerun-if-changed={}", themes_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(rd) = fs::read_dir(&themes_dir) {
        for e in rd.flatten() {
            let path = e.path();
            if !path.is_file() {
                continue;
            }
            let name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };
            if name == "LICENSE" || name == "README.md" {
                continue;
            }
            if let Ok(contents) = fs::read_to_string(&path) {
                entries.push((name, contents));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// @generated by build.rs\n");
    out.push_str(&format!(
        "pub static BUNDLED_THEMES: [(&str, &str); {}] = [\n",
        entries.len()
    ));
    for (name, contents) in &entries {
        out.push_str(&format!(
            "    ({:?}, {:?}),\n",
            name,
            contents.replace('\r', "")
        ));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("themes_generated.rs"), out).unwrap();
}
